### ISSUE TITLE
running through Falcon RTR does not provide the expected results

### ISSUE THREAD

**Issue by borutlape1** [CrowdStrike/CAST#10]
Hi,

We have ran the script though Falcon RTR on few vulnerable servers and did not detect anything.
The reason in every case was that the library is not present in the same folder as the executable, (e.g. .exe in \bin folder, .jar in \lib folder)

Is there a possibility to run the script through RTR with our own arguments, to scan a specific folder? It will be very useful.

According the manual there is an option to fill -CommandLine="", but I could not find its usage in the PS script...

Thanks,
Borut

**Comment by rbcrwd** [comment]
Identifying vulnerable libraries is not dependent on the placement of the binary, nor even on the script wrapper.

If you're using the PS1 wrapper, it attempts to serve as a one-size solution by enumerating running processes and known configuration locations to select paths to scan. As such, it can miss latent JAR files, particularly those just placed in a semi-arbitrary location for testing.

You may invoke the `cast.exe` executable directly via RTR's `run` command and give it one or more paths to scan, or you may drop your own PS1 that invokes it against, say, `C:\lib` and execute that via `runscript`.

**Comment by borutlape1** [comment]
Already tried running cast.exe directly, am I missing something?

C:\temp> run cast.exe scan c:\temp
Max args is 1. 3 were provided
Error code: 40012

**Comment by rbcrwd** [comment]
I wasn't aware of that limitation with the RTR `run` verb; it looks like you'll have to drop a dedicated script for your testing (or place your known-vulnerable JAR in the installation path of a running Java application).

**Comment by rbcrwd** [comment]
I've asked that the RTR documentation be updated, but there is actually a correct way to solve this with `run`:

`run C:\cast.exe -CommandLine='scan C:\path\to\malicious.zip'`

**Comment by borutlape1** [comment]
Thanks for the effort, successfully ran, but unfortunately the command does not give any output in the RTR console :(
Will have to go with a Powershell script after all...
