### ISSUE TITLE
CAST did not detect log4j file compressed in JAR

### ISSUE THREAD

**Issue by rc15june** [CrowdStrike/CAST#11]
We have a server on which CAST did not detect log4j file compressed within JAR file

**Comment by rbcrwd** [comment]
Unfortunately you’re going to need to be a lot more precise - how you ran CAST, where the file was, what it contained, why you think it should have been caught, and so on. It would also be strongly helpful to upload a copy of this presumptive JAR. 

Alternatively, if you are a CS customer and prefer to not publish those details you can work with your sales engineer to close this loop. 

[edit]
Please see the details expected in the new bug-report template.

**Comment by rbcrwd** [comment]
Lacking any further detail submission, I'm closing this. Please follow the new-issue template if you believe this is in error.
