### ISSUE TITLE
Use of Win32_Product Class 

### ISSUE THREAD

**Issue by Snuffler** [CrowdStrike/CAST#12]
The script uses the Win32_Product Class
Get-CimInstance -ClassName Win32_Product -Filter "InstallLocation like '%'").InstallLocation

This class should NOT be used
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa394378(v=vs.85)
https://docs.microsoft.com/en-GB/troubleshoot/windows-server/admin-development/windows-installer-reconfigured-all-applications
https://docs.microsoft.com/en-gb/archive/blogs/askds/how-to-not-use-win32_product-in-group-policy-filtering

**Comment by bk-cs** [comment]
Thank you for the report. I've updated the script to use the new class.
