### ISSUE TITLE
PS Script Error "Invalid class You cannot call a method on a null-valued expression"

### ISSUE THREAD

**Issue by G3nrlPs0** [CrowdStrike/CAST#13]
When running the "Find-VulnerableLog4j.ps1" script via RTR on Windows 10 endpoints, I receive the following error: "Invalid class You cannot call a method on a null-valued expression." (see screen shot) Only modification to the PS script is the instructed tempdirectorypath variable setting (I set to $TempDirectoryPath = "c:\cast"). Cast.exe was placed in that directory, and the script was run from that directory as well.

Thanks,
-Brock

![PS-Error](https://user-images.githubusercontent.com/97068865/147994805-77e96e5e-8d45-4a43-8c55-16482bf101a6.jpg)

**Comment by bk-cs** [comment]
Thanks for the report!

I updated the script to use a different method to search for installed/running programs. Could you try the new script and let me know if you still have any issues?

https://github.com/CrowdStrike/CAST/blob/main/deploy/Find-VulnerableLog4J.ps1

**Comment by G3nrlPs0** [comment]
You bet, and thanks for the fix! =D  Just ran the new script and it completed successfully.   \ ^o^/

![PS-Fixed](https://user-images.githubusercontent.com/97068865/148106463-b1cc43c6-5820-4f1d-ba22-20e10003f5e1.jpg)
