### ISSUE TITLE
code 40006 and message: command is not valid

### ISSUE THREAD

**Issue by rc15june** [CrowdStrike/CAST#15]
I am trying to run the script via PSFalcon "Invoke-FalconRtr runscript “-CloudFile=’log4j’” -HostIds xxxxxxxxxxxxxxxx" but getting an error

**Comment by bk-cs** [comment]
An error code like `40006` is usually one generated by the Real-time Response API. 

Please verify the following:
* The `runscript` option has been enabled within your Real-time Response policy that is assigned to the target device(s)
* The script name exactly matches `log4j` (including case) in your "Response Scripts & Files"
* The script's permission level is not set to "Only me"
* The API client being used with PSFalcon has permissions that match the permission level of the script

**Comment by bk-cs** [comment]
Did any of these suggestions help? Please let me know. I'll wait until the end of the day to close this issue if you don't respond back. Thanks!
