### ISSUE TITLE
Script stops when the path doesn't exist

### ISSUE THREAD

**Issue by abordon4** [CrowdStrike/CAST#16]
I'm using the script with cast_0.6.2_Windows_amd64.zip. I've tried to run it in multiple machines where I have intentionally copied .jar files and it always error out with the following message
"The system cannot find the path specified." and that seems to terminate the script. 

I always get 0 files scanned. 

Please, advise. 

C:\> put "cast.exe"
Operation completed successfully.

C:\> runscript -CloudFile="Find-VulnerableLog4J" -CommandLine=""

Searching 60 directories...

2022/01/07 10:37:16 archives: 2 found: 0 scanned: 17336 skip: 02022/01/07 10:37:16 error starting C:\Program Files\Realtek\Audio\USB: CreateFile C:\Program Files\Realtek\Audio\USB: The system cannot find the path specified.
C:\>

**Comment by bk-cs** [comment]
I believe this is a case of `cast.exe` stopping, not the script. You can run `cast.exe` without the script using Real-time Response to verify:

```
put cast.exe
runscript -Raw=```C:\cast.exe scan C:\```
```

Since it will likely output a lot of information, you can also save the results to a text file:
```
put cast.exe
runscript -Raw=```C:\cast.exe scan C:\ *>&1 | Out-File C:\cast.txt```
```

You may notice a "native command error" at the end of the text file. I'm not sure where that's being generated yet, but it doesn't seem to affect the output.

Using one of these methods should prevent the `The system cannot find the path specified` error from being generated because it's not gathering a list of files to scan before scanning them, and thus likely won't be subject to files being moved/deleted while the scan is being run on the targets.

**Comment by abordon4** [comment]
I tried that but to run it that way but it times out 

C:\> runscript -Raw=```C:\cast.exe scan C:\```

Timed out waiting for script to complete

C:\> runscript -Raw=```C:\cast.exe scan C:\ *>&1 | Out-File C:\cast.txt```

Timed out waiting for script to complete

C:\> ls cast.txt
Directory listing for C:\cast.txt -

Name                                     Type            Size (bytes)       Size (MB) Last Modified (UTC-6)     Created (UTC-6)          
----                                     ----            ------------       --------- ---------------------     ---------------          
cast.txt                                 .txt                       0               0 1/10/2022 2:36:21 PM      1/10/2022 2:36:21 PM

**Comment by bk-cs** [comment]
You can start a secondary process which should do it for you:

```
runscript -Raw=```Start-Process -FilePath C:\cast.exe -ArgumentList 'scan C:\ *>&1 | Out-File C:\cast.txt' -PassThru```
```

EDIT: The output to text isn't working for me in this example when I try it--I'll have to experiment.

**Comment by bk-cs** [comment]
Here's a corrected example of how you can start the scan without the risk of timing out:

```
runscript -Raw=```Start-Process -FilePath C:\cast.exe -ArgumentList 'scan C:\' -RedirectStandardOutput C:\cast.txt -PassThru```
```

**Comment by abordon4** [comment]
I used invoke-command and it ran but as you can see it did not scan any of the vulnerable files I had in C:\Users\testuser\Downloads\testfiles

C:\> runscript -Raw=```Start-Process -FilePath C:\cast.exe -ArgumentList 'scan C:\ *>&1 | Out-File C:\cast.txt' -PassThru```
System.Diagnostics.Process (cast)

C:\> runscript -Raw=``` Invoke-Command {C:\cast.exe scan c:\ | Out-File C:\cast.txt}```

2022/01/11 11:27:42 archives: 52 found: 0 scanned: 508757 skip: 0

C:\> ls cast.txt
Directory listing for C:\cast.txt -

Name                                     Type            Size (bytes)       Size (MB) Last Modified (UTC-6)     Created (UTC-6)          
----                                     ----            ------------       --------- ---------------------     ---------------          
cast.txt                                 .txt                       0               0 1/11/2022 11:26:18 AM     1/11/2022 11:26:18 AM    

C:\> cat cast.txt

C:\> 


Directory: C:\Users\testuser\Downloads\testfiles

Mode                 LastWriteTime         Length Name                                                                                                                                                      
----                 -------------         ------ ----                                                                                                                                                      
-a----         1/11/2022  10:48 AM       68942964 bundle.jar                                                                                                                                             
-a----         1/11/2022  10:52 AM       82872888 HN.war                                                                                                                                               
-a----         1/11/2022  10:41 AM        1762733 log4j_core_2.14.0.jar                                                                                                                                     



PS C:\WINDOWS\system32>

**Comment by abordon4** [comment]
This command line didn't produce any results 

C:\> runscript -Raw=```Start-Process C:\cast.exe -ArgumentList 'scan C:\ *>&1 | Out-File C:\cast.txt'```
C:\> ls cast.txt
Check the path. 'cast.txt' does not exist
C:\> 

I ran it using invoke-command and it looks like it ran but didn't scan any of the vulnerable files stored under Directory: C:\Users\testuser\Downloads\testfiles

Mode                 LastWriteTime         Length Name                                                                                                                                                      
----                 -------------         ------ ----                                                                                                                                                      
-a----         1/11/2022  10:48 AM       68942964 bundle.jar                                                                                                                                             
-a----         1/11/2022  10:52 AM       82872888 HN.war                                                                                                                                               
-a----         1/11/2022  10:41 AM        1762733 log4j_core_2.14.0.jar    

C:\> runscript -Raw=``` Invoke-Command {C:\cast.exe scan c:\ | Out-File C:\cast.txt}```

2022/01/11 11:27:42 archives: 52 found: 0 scanned: 508757 skip: 0

C:\> ls cast.txt
Directory listing for C:\cast.txt -

Name                                     Type            Size (bytes)       Size (MB) Last Modified (UTC-6)     Created (UTC-6)          
----                                     ----            ------------       --------- ---------------------     ---------------          
cast.txt                                 .txt                       0               0 1/11/2022 11:26:18 AM     1/11/2022 11:26:18 AM    

C:\> cat cast.txt

C:\>

**Comment by bk-cs** [comment]
> This command line didn't produce any results
> 
> C:> runscript -Raw=`Start-Process C:\cast.exe -ArgumentList 'scan C:\ *>&1 | Out-File C:\cast.txt'` C:> ls cast.txt Check the path. 'cast.txt' does not exist C:>

I noted that my original example didn't work in my earlier response. My followup had a proper example. Please retry with this one:
```
runscript -Raw=```Start-Process -FilePath C:\cast.exe -ArgumentList 'scan C:\' -RedirectStandardOutput C:\cast.txt -PassThru```
```

**Comment by abordon4** [comment]
Thanks! It's working
