### ISSUE TITLE
Do we need Crowdstrike Sensor to use this tool?

### ISSUE THREAD

**Issue by piyu200594** [CrowdStrike/CAST#20]
Can you please give the Linux steps installations and usage of this tool? Also I don't find any file for Linux? How do we install the ps1 in a linux host.

**Comment by bk-cs** [comment]
* The Falcon Sensor is not required to use this tool.
* The PowerShell script is designed to help narrow the scope of the scan, but is only for Windows devices.
* Linux releases can be found here: https://github.com/CrowdStrike/CAST/releases
* Linux instructions can be found here: https://github.com/CrowdStrike/CAST#usage
