### ISSUE TITLE
Unable to install on pc

### ISSUE THREAD

**Issue by PaulyPaul9** [CrowdStrike/CAST#21]
Can someone please assist me in, installing the utility tool, i have run it with admin and am still unable to install the tool. Is there something i am doing wrong i have downloaded (cast_0.6.2_Windows_amd64)  unzipped it the cast.exe is present however I am unable to do anything further.  

Thank you in advance!

PP9

**Comment by bk-cs** [comment]
This tool is built to run using command line parameters and doesn't need to be installed on the computer. If you've unpacked the archive, you can initiate a scan by using the parameters outlined in the README: https://github.com/CrowdStrike/CAST#usage
