### ISSUE TITLE
source code missing for Darwin / Linux

### ISSUE THREAD

**Issue by jschauma** [CrowdStrike/CAST#25]
https://github.com/CrowdStrike/CAST/releases includes binaries for Linux and Darwin, but the source code appears to only include the powershell script, not the actual sources for CAST?

**Comment by rbcrwd** [comment]
CAST is a binary-only release. We have no intention to release the source.

**Comment by jschauma** [comment]
Ah, thanks for the clarification. I guess I was confused by the phrasing on the project homepage "As an open source project this software is not officially supported by CrowdStrike."

**Comment by rbcrwd** [comment]
Understood. That text was added during my PTO, and I will adjust it to be correct. It is a free, as-is tool, not an open-source one.
