### ISSUE TITLE
Possibility for mass distribution? 

### ISSUE THREAD

**Issue by jamo-ginger11** [CrowdStrike/CAST#27]
Viewing the deployment of the script, I see that this script references the deployment through a singular endpoint. Is there a possible way to push this out to a wider infrastructure (i.e. SCCM)?

**Comment by rbcrwd** [comment]
While I'm not certain what you mean by "singular endpoint", this tool was developed to be agnostic of the deployment mechanism. You, as the sysadmin, know best what you are doing in your environment, and we cannot prescribe how to manage your environment.

The executable is designed in POSIX tradition to be placed on-system and called with one or more arguments, with the calling program capturing the program's STDOUT and STDERR.  The deployment PS1 illustrates one such way to execute it. Whether you choose to use the PS1 or deploy the EXE yourself is completely up to you.

That is to say, go crazy. Do whatever you need with SCCM or similar mechanisms to deploy this; we are intentionally staying out of your way.
