### ISSUE TITLE
Getting error "Program 'cast.exe' failed to run: The filename or extension is too long.."

### ISSUE THREAD

**Issue by anurbiswas** [CrowdStrike/CAST#3]
**Describe the bug**
Getting an error as subject while running the scan on a windows server. Is there a filename length limitation?

**To Reproduce**

**Expected behavior**
Expected to scan successfully

**Screenshots**
<img width="842" alt="image" src="https://user-images.githubusercontent.com/77502175/147293778-88e2b52f-15d5-4b0b-9bfc-cd9b3511b6c2.png">

**Desktop (please complete the following information):**
 - OS: Windows 2012 R2

**Comment by rbcrwd** [comment]
Windows itself has a command length limitation that you're running into. We're working on a workaround, but please just invoke the CAST binary yourself against the drives or directories you wish to scan.

**Comment by bk-cs** [comment]
I just added a commit and pull request to break the scans into groups of 20 files. This should avoid most string limitations.

**Comment by rbcrwd** [comment]
@bk-cs's PR should have addressed this sufficiently. Please let us know if you continue to see the error.
