### ISSUE TITLE
Virustotal tags file as malicious

### ISSUE THREAD

**Issue by sokatra** [CrowdStrike/CAST#5]
**Describe the bug**
Virustotal tags the windows exe as malicious

**To Reproduce**
check https://www.virustotal.com/gui/file/86fe23eaf103f69da6d81ed95cf2418185dc879b00d8d22156b1496e4dd0fefa?nocache=1
File cast.exe in cast_0.6.0_Windows_amd64.tar
**Expected behavior**
no virus should be detected

**Screenshots**

**Additional context**

**Comment by rbcrwd** [comment]
We can't control other vendors' actions. If you find the tool unsafe, please do not use it.
